#+TITLE: Self Made Person
#+AUTHOR: Aarti Anand
#+EMAIL: rtofficials@gmail.com
#+SETUPFILE: https://rtofficials.github.io/static/theme.setup
#+BEGIN_CENTER
[ [[https://rtofficials.github.io][home]] / [[https://rtofficials.github.io/about.html][about]] / [[https://rtofficials.github.io.com/contact.html][contact]] ]
#+END_CENTER

* Self Made Person
  /Genre : Inspirational, Fiction, Drama/

  “Martha James Hudson. She is such a burden.”

  “You know why we are bringing her up.” Austin, Martha’s uncle pointed at his wife, Kate.

  “Yeah, Yeah, the gold she has”


  They thought Martha didn’t know anything; but she used to pretend to be sleeping, and listened to all their conversations. After her parents' death in that accident, only she lived. Her parents were rich and Martha was their only daughter. They loved her a lot. For her, it’s asked-and-done.
  She didn’t leave the room all day except for meals. She didn’t make any friends in that locality after she shifted to her Uncle’s. Her father died on the spot of the accident, her mother was in a critical stage when she was taken to the hospital. Hours after that, Martha lost her too. 13-year old Martha was unconscious on the hospital bed when she lost her parents. The start of teenage years brings many changes to the body and mind of a kid. And at this start, she was all alone. Even after living in a family, she didn't feel to be in a family - secure, safe and happy.
  Her uncle was younger than her father. He always felt envious of him.  Martha’s father has always been a mature and loving person, being older. While her uncle was not organised, neither in career nor in thoughts. This childhood envy turned into hate. That accident wasn’t just happening.  It was a plan. I believe as a reader you understand what I meant, do you?
  Martha knew all this, except that the accident was planned.


  Her father named all his property to Martha. And that was the reason Austin and Kate fed her.
  All day in her room, Martha kept looking outside. There was a boy next door who took care of his garden. He was 19 years old. Martha loves to watch the garden getting cleaned everyday - A small mountain of Brown dead leaves, wiping the grass off the dew, picking out the weeds and watering the plants. He loved plants and greenery and it seemed that the plants and grass and every member of that garden loved him back. The baby kittens who would be just a month old play with him. He fed them with small bits of bread crumbs, while the momma cat used to sleep in the soft sunshine. This hour of her life has been constant since she moved to her uncle’s and this hour has been the only hour she smiles - One could see that she used to forget all that happened with her. She wanted to go there, talk to that guy and help him do the garden and play with the kittens and see momma cat sleep. But she didn’t. I remember that she once gathered courage to go there and live the moment. She went there, gazed from a distance when Sam asked him what she wanted. It was then conversation started and they started to share the bond of friendship. She told what happened to her parents and how her life is now and he told her that it’s not his fondness to take care of the garden but her mom loved to do so. His father used to drink a lot and one day he drank a lot and hit her mother and left home. As he was crossing the road, a truck hit him. This took his mother’s senses and now she is mentally ill. So he used to take care of her and the garden.
  The two had their own stories so different but they felt connected. Her uncle and aunt didn’t like her friendship with him. If it were old Martha, she must have stopped talking and confined herself to her bed again. But after meeting with Sam, she started to feel like fighting with problems and enjoying the life she had. Soon, she got admitted into a school and continued her studies. Her routine now changed to get up early, do the garden with Sam and go to school. And when she returned from school she shared what happened in school and at points they giggled and laughed for long.
  I remember that day, she came to school. She was quieter than usual. I thought it must be her period but in the break she told me that her parents didn’t die in a car accident rather it was all planned. As she was getting ready, she overheard her uncle and aunt. She knew that they were after her parents’ property but they would fall to such an extent, as wasn't expected. She didn’t cry that day. She told me. Not even when she overheard them. Not even when she was telling me all this. I could see it in her eyes, She grew up. And I believe it all was because of Sam. That evening she told all this to Sam. They had a conversation for an hour or so and it was then, I never saw Martha’s childish behaviour after then. I liked how she got good company from Sam and how she was getting moulded into a responsible mature person. She started to pay attention to her studies. As she crossed her eighteen, she found herself a  job that paid enough for a person to live a good life. She started saving money and soon shifting to a house on rent. She was independent now. She even got a scholarship that she completed at college with her own savings and job. Even though her parents left her enough wealth, I never saw her use it extravagantly. Rather she tried to add to it. I’m sure her parents would be so proud of her. We do not talk much now. We both are busy with our lives. But last Sunday, she told me that she is getting married to Sam. I was surprised. She never told me they were in a relationship. But I am so excited and happy for her. She is a self made person and I wish good for her. Oh! By the way, I forgot to mention, I’m Kelly. Martha’s best friend.


